version: 2
sphinx:
  configuration: docs/conf.py
formats:
  - htmlzip
build:
  image: latest
python:
  version: 3.7
  install:
    - method: pip
      path: .
    - method: pip
      requirements: requires/docs.txt
