[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sprockets.mixins.mediatype"
version = '3.0.5'
description = "A mixin for reporting handling content-type/accept headers."
readme = "README.rst"
license = "BSD-3-Clause"
authors = [{ name = "AWeber Communications", email = "api@aweber.com" }]
requires-python = ">=3.9"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["ietfparse>=1.5.1,<2", "tornado>=5,<7"]

[project.urls]
Changelog = "https://sprocketsmixinsmedia-type.readthedocs.io/en/latest/history.html"
Documentation = "https://sprocketsmixinsmedia-type.readthedocs.io"
Download = "https://pypi.org/project/sprockets.mixins.mediatype/"
Homepage = "https://github.com/sprockets/sprockets.mixins.mediatype"
Source = "https://github.com/sprockets/sprockets.mixins.mediatype"

[project.optional-dependencies]
msgpack = ["u-msgpack-python>=2.5.0,<3"]
ci = [
  "coverage[toml]>7.10",
  "mypy>=1.18,<1.19",
  "pydantic>=2,<3",
  "ruff>=0.12.11,<0.13",
]
dev = [
  "coverage>=7.10",
  "mypy>=1.18,<1.19",
  "pre-commit==4.3.0",
  "pydantic>=2,<3",
  "ruff>=0.12.11,<0.13",
  "sphinx>=7.4,<9",
  "sphinx-rtd-theme>=3.0.2,<4",
  "sphinxcontrib-httpdomain>=1.8.1,<2",
]
docs = [
  "sphinx>=8.2.3,<9",
  "sphinx-rtd-theme>=3.0.2,<4",
  "sphinxcontrib-httpdomain>=1.8.1,<2",
]

[tool.hatch.build.targets.wheel]
packages = ["sprockets"]

[tool.coverage.run]
branch = true
omit = ["sprockets/mixins/mediatype/type_info.py"]
source = ["sprockets"]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.mypy]
mypy_path = "typestubs"
show_error_codes = true
strict = true

[tool.ruff]
line-length = 79
target-version = "py39"

[tool.ruff.format]
quote-style = 'single'

[tool.ruff.lint]
select = [
  "A",
  "ANN",
  "ARG",
  "ASYNC",
  "B",
  "BLE",
  "C4",
  "C90",
  "DTZ",
  "E",
  "ERA",
  "F",
  "FLY",
  "FURB",
  "G",
  "I",
  "LOG",
  "N",
  "PIE",
  "PL",
  "PTH",
  "Q",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "T10",
  "T20",
  "TC",
  "TRY",
  "W",
]
ignore = [
  "TRY003", # messages in exception initializers are okay
  "TRY400", # logging.exception is not always preferrable
]
flake8-quotes = { inline-quotes = "single" }

[tool.ruff.lint.per-file-ignores]
"tests.py" = ["ARG002", "BLE"]
